### ISSUE TITLE
HTTPSession issue

### ISSUE THREAD

**Issue by jflefebvre06** [GoogleCloudPlatform/jetty-runtime#161]
Hello,

I have write the very simple servlet bellow :
```
@WebServlet(name = "index", value = "")
public class IndexServlet extends HttpServlet {
	@Override
	public void doGet(HttpServletRequest req, HttpServletResponse resp) throws IOException {
		final PrintWriter out = resp.getWriter();
		HttpSession session= req.getSession(true);
		out.println("Session id : " + session.getId());
		out.println("Session new : " + session.isNew());
		AtomicInteger ato=(AtomicInteger) session.getAttribute("ATO");		
		if(ato==null){			
			out.println("ato null");
			ato= new AtomicInteger();
		}else{
			out.println("ato before " + ato.get());	
		}
		ato.incrementAndGet();
		session.setAttribute("ATO", ato);
		out.println("ato after " + ((AtomicInteger) session.getAttribute("ATO")).get());	
	}
}
```

The servet create a new session if not exist and put an incremental integer.

The servlet is deployed into flexible environmment (2 instances) :
```
# [START runtime]
runtime: java
env: flex

handlers:
- url: /.*
  script: this field is required, but ignored
manual_scaling:
  instances: 2
# [END runtime]
```

When I browse my servlet, and I refresh the page,  I can see that the session id change :
Session id **node05amknapl2nae1w36p9h06jc4413**
Session new true

Session id **node0k5vvl8mqww941bw2mmrsinaun7**
Session new true

I understand it is because nginx sticky session future is not configured.

What can I do to share HttpSession between my 2 instances ?

Thanks

**Comment by aslo** [comment]
Hi @jflefebvre06, 

Since there's currently no sticky sessions in App Engine Flexible, sessions would need to be persisted using a storage mechanism that's visible to all instances running your application. We are currently working on supporting that feature out-of-the-box in the jetty runtime using Google Cloud Datastore - see #41 for more detail. Unfortunately, until that time, you would need to manually handle session persistence.

@meltsufin or @janbartel may have more info.

**Comment by jflefebvre06** [comment]
Hi @aslo 

I have try to use "session-store-gcloud" but it is not seems to work very well.

My dockerfile :
```
FROM gcr.io/google-appengine/jetty
ADD test-0.0.1-SNAPSHOT.war $JETTY_BASE/webapps/root.war
WORKDIR $JETTY_BASE
RUN java -jar $JETTY_HOME/start.jar --approve-all-licenses --add-to-start=slf4j-jul,session-store-gcloud
```

My app.yaml :
```
# [START runtime]
runtime: custom
env: flex

service: test

handlers:
- url: /.*
  script: this field is required, but ignored

resources:
  cpu: 1
  memory_gb: 0.6

health_check:
  enable_health_check: False

manual_scaling:
  instances: 2

# [END runtime]
```

Anything else to do ?
